module Evergreen.Migrate.V6 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V2.Types
import Evergreen.V6.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V2.Types.FrontendModel -> ModelMigration Evergreen.V6.Types.FrontendModel Evergreen.V6.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V2.Types.BackendModel -> ModelMigration Evergreen.V6.Types.BackendModel Evergreen.V6.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V2.Types.FrontendMsg -> MsgMigration Evergreen.V6.Types.FrontendMsg Evergreen.V6.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V2.Types.ToBackend -> MsgMigration Evergreen.V6.Types.ToBackend Evergreen.V6.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V2.Types.BackendMsg -> MsgMigration Evergreen.V6.Types.BackendMsg Evergreen.V6.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V2.Types.ToFrontend -> MsgMigration Evergreen.V6.Types.ToFrontend Evergreen.V6.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V2.Types.FrontendModel -> Evergreen.V6.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , route = old.route |> migrate_Types_Route
    , online = old.online
    , playgrounds = []
    , myLocation = Just { lat = 0, lng = 0 }
    }


migrate_Types_FrontendMsg : Evergreen.V2.Types.FrontendMsg -> Evergreen.V6.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V2.Types.UrlClicked p0 ->
            Evergreen.V6.Types.UrlClicked p0

        Evergreen.V2.Types.UrlChanged p0 ->
            Evergreen.V6.Types.UrlChanged p0

        Evergreen.V2.Types.Capture p0 ->
            Evergreen.V6.Types.NoOpFrontendMsg

        Evergreen.V2.Types.CreateCapture ->
            Evergreen.V6.Types.NoOpFrontendMsg

        Evergreen.V2.Types.Online p0 ->
            Evergreen.V6.Types.Online p0

        Evergreen.V2.Types.ReplaceUrl p0 ->
            Evergreen.V6.Types.ReplaceUrl p0

        Evergreen.V2.Types.NoOpFrontendMsg ->
            Evergreen.V6.Types.NoOpFrontendMsg


migrate_Types_Route : Evergreen.V2.Types.Route -> Evergreen.V6.Types.Route
migrate_Types_Route old =
    case old of
        Evergreen.V2.Types.MainRoute ->
            Evergreen.V6.Types.MainRoute

        Evergreen.V2.Types.PlaygroundRoute p0 ->
            Evergreen.V6.Types.PlaygroundRoute p0

        Evergreen.V2.Types.AwardsRoute ->
            Evergreen.V6.Types.AwardsRoute

        Evergreen.V2.Types.NewAwardRoute p0 ->
            Evergreen.V6.Types.NewAwardRoute p0
