spin_manifest_version = 2

[application]
name = "magdeburger-spielplatznadel"
version = "0.1.0"
authors = ["Janek Winkler <janekx21@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "web"

[component.web]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "web/public", destination = "/" }]
[component.web.build]
command = "elm make src/Main.elm --output public/elm.js --optimize"
workdir = "web"
watch = ["src/**/*.elm"]

[[trigger.http]]
route = "/api/..."
component = "backend"

[component.backend]
source = "backend/target/wasm32-wasi/release/backend.wasm"
allowed_outbound_hosts = []
[component.backend.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "backend"
watch = ["src/**/*.rs", "Cargo.toml"]
