on:
  push:
    branches:
    - main
    - release/*
jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Env
      uses: JRMurr/direnv-nix-action@v4.1.0
    - name: Build Frontend
      run: build-frontend
      shell: bash
    # - uses: workflow/nix-shell-action@v3
    #   with:
    #     flakes-from-devshell: true
    #     script: |
    #       # Runs build from a local flake.nix with a `devShell`
    #       mkdir dist
    #       elm make src/Main.elm --output dist/elm.js --optimize
    #       cp index.html dist
    #       cp -r assets dist
    #       cp *.js dist
    #       cp manifest.json dist
    # - run: |
    #    nix develop --impure --accept-flake-config
    #    build-frontend
