on:
  push:
    branches:
    - main
    - release/*
defaults:
  run:
    working-directory: apps/frontend
jobs:
  deploy-to-staging:
    working-directo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - run: nix develop --impure
    - run: buid-frontend
