on:
  push:
    branches:
    - main
    - release/*
defaults:
  run:
    working-directory: apps/frontend
jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nix
      uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: workflow/nix-shell-action@v3
      with:
        flakes-from-devshell: true
        script: |
          # Runs build from a local flake.nix with a `devShell`
          mkdir dist
          elm make src/Main.elm --output dist/elm.js --optimize
          cp index.html dist
          cp -r assets dist
          cp *.js dist
          cp manifest.json dist
    # - run: |
    #    nix develop --impure --accept-flake-config
    #    build-frontend
