on:
  push:
    branches:
    - main
    - release/*
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Env
      uses: JRMurr/direnv-nix-action@v4.1.0
    - name: Build Frontend
      run: build-frontend
      shell: bash
    - name: Deploy to Github Pages
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: app/frontend/dist
              
