on:
  push:
    branches:
    - main
    - release/*
defaults:
  run:
    working-directory: apps/frontend
jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: aldoborrero/use-nix-action@v4
    - run: build-frontend
